# Generated by Django 3.2.4 on 2021-06-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('birthDate', models.DateTimeField(blank=True, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
